# Generated by Django 2.1.5 on 2019-02-03 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('code_reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Question_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='task',
            name='status_color',
            field=models.CharField(default='red', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='tests_success',
            field=models.TextField(default='[]', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='user_list',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='solve_status',
            field=models.CharField(default='no run', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='timeout',
            field=models.FloatField(default=3.0),
        ),
    ]
