# Generated by Django 2.1.5 on 2019-02-03 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_reception', '0002_auto_20190203_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user_list',
            new_name='user_set',
        ),
    ]
