# Generated by Django 2.1.5 on 2019-03-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_reception', '0004_testcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='correct_answer',
            field=models.TextField(default=''),
        ),
    ]
