# Generated by Django 2.1.5 on 2019-03-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_reception', '0006_auto_20190304_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='code',
            field=models.TextField(default=''),
        ),
    ]
