# Generated by Django 2.1.5 on 2019-03-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_reception', '0007_task_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='code',
        ),
    ]
